name: Deploy

on:
  push:
      branches: [ main ]

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Setup project
          uses: actions/checkout@v2
        
        - name: create env file
          run: |
            touch .env
            echo botToken=${{ secrets.DISCORD_BOT_TOKEN }} >> .env
          shell: bash
        
        - name: copy files to remote server
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_KEY }}
            source: .
            target: /home/projects