name: Deploy

on:
  push:
      branches: [ main ]

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Setup project
          uses: actions/checkout@v2
        
        - name: create env file
          run: |
            touch .env
            echo botToken=${{ secrets.DISCORD_BOT_TOKEN }} >> .env
          shell: bash